// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNW5Zz9UN1lWyquiyTA3iAvzyb6md8vsE',
    appId: '1:199935318252:web:61dd44b25401bae9f22dc9',
    messagingSenderId: '199935318252',
    projectId: 'chatapp-1c28b',
    authDomain: 'chatapp-1c28b.firebaseapp.com',
    storageBucket: 'chatapp-1c28b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiKhIrzkP_thcF18luh74AX7CNsDB8uL8',
    appId: '1:199935318252:android:0b9c1f715b94b99cf22dc9',
    messagingSenderId: '199935318252',
    projectId: 'chatapp-1c28b',
    storageBucket: 'chatapp-1c28b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTUGWgJc264cf-GsNQGX6xtxJVoBfzQlk',
    appId: '1:199935318252:ios:d60885ea9602604bf22dc9',
    messagingSenderId: '199935318252',
    projectId: 'chatapp-1c28b',
    storageBucket: 'chatapp-1c28b.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTUGWgJc264cf-GsNQGX6xtxJVoBfzQlk',
    appId: '1:199935318252:ios:fc41845560810e8df22dc9',
    messagingSenderId: '199935318252',
    projectId: 'chatapp-1c28b',
    storageBucket: 'chatapp-1c28b.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
